version: "3"
services:
    api:
        build: .
        ports: 
             - "800:800" 
    db:
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "MarketFlight10"
            ACCEPT_EULA: "Y"